WebApplication2/WebApplication2/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Sanpham()
        {
            return View();
        }
        public ActionResult Khachhang()
        {
            return View();
        }
        public ActionResult Hoadon()
        {
            return View();
        }
        public ActionResult Tintuc()
        {
            return View();
        }
        public ActionResult Nghenhan()
        {
            return View();
        }
        public ActionResult Dactinh()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Loginkh()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }

    }
}

WebApplication2/WebApplication2/Views/Default/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<body>
    <h1>Home</h1>
</body>
</html>

WebApplication2/WebApplication2/Views/Default/Login.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/~/assets/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap"
          rel="stylesheet" />

    <link rel="stylesheet" href="~/assets/fonts/icomoon/style.css" />

    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css" />

    <!-- Style -->
    <link rel="stylesheet" href="~/assets/css/styleLogin.css" />

    <title>Admin Login</title>

    <script type="text/javascript">
        function Login() {
            var userName = $('#username').val();
            var passWord = $('#password').val();
            // Gửi yêu cầu đăng nhập đến API
            $.ajax({

                type: 'POST',
                url: 'https://localhost:44336/api/Account/Login',
                data: JSON.stringify({ Username: userName, Password: passWord }),
                contentType: 'application/json',
                dataType: 'json',
                success: function (data) {
                    // Lưu thông tin tài khoản và token vào Local Storage để sử dụng cho các lần yêu cầu khác

                    localStorage.setItem('userToken', data.Token);

                    // Chuyển hướng đến trang chủ hoặc trang được yêu cầu trước đó
                    window.location.href = 'https://localhost:44386/Default/Index';
                },
                error: function (xhr, status, error) {
                    alert('Lỗi đăng nhập: ' + xhr.responseText);
                }
            });
        }
    </script>

</head>

<body>
    <a href="@Url.Action("Loginkh", "Default")" class="sigIn-user"><i class="fa-solid fa-arrow-left"></i> Sign In to User</a>
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-md-6 order-md-2">
                    <img src="~/assets/img/undraw_file_sync_ot38.svg"
                         alt="Image"
                         class="img-fluid" />
                </div>
                <div class="col-md-6 contents">
                    <div class="row justify-content-center">
                        <div class="col-md-8">
                            <div class="mb-4">
                                <h3>Sign In to <strong>Admin</strong></h3>
                                <p class="mb-4">
                                    Lorem ipsum dolor sit amet elit. Sapiente sit aut eos
                                    consectetur adipisicing.
                                </p>
                            </div>
                            <form action="#" method="post">
                                <div class="form-group first">
                                    <label for="username">Username</label>
                                    <input type="text" class="form-control" id="username" />
                                </div>
                                <div class="form-group last mb-4">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control" id="password" />
                                </div>

                                <div class="d-flex mb-5 align-items-center">
                                    <label class="control control--checkbox mb-0">
                                        <span class="caption">Remember me</span>
                                        <input type="checkbox" checked="checked" />
                                    </label>
                                    <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
                                </div>

                                <button id="btn-login" onclick="Login();">Đăng nhập</button>

                                <span class="d-block text-left my-4 text-muted">
                                    or sign in with
                                </span>

                                <div class="social-login">
                                    <a href="#" class="facebook">
                                        <span class="icon-facebook mr-3"></span>
                                    </a>
                                    <a href="#" class="twitter">
                                        <span class="icon-twitter mr-3"></span>
                                    </a>
                                    <a href="#" class="google">
                                        <span class="icon-google mr-3"></span>
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/assets/js/jquery-3.3.1.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/main.js"></script>
</body>

</html>

WebApplication2/WebApplication2/Views/Default/Loginkh.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/~/assets/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap"
          rel="stylesheet" />

    <link rel="stylesheet" href="~/assets/fonts/icomoon/style.css" />

    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css" />

    <!-- Style -->
    <link rel="stylesheet" href="~/assets/css/styleLogin.css" />

    <title>User Login</title>

    <script type="text/javascript">
        function Login() {
            var userName = $('#username').val();
            var passWord = $('#password').val();
            // Gửi yêu cầu đăng nhập đến API
            $.ajax({

                type: 'POST',
                url: 'https://localhost:44336/api/Accountkh/Login',
                data: JSON.stringify({ Username_khach: userName, Password_khach: passWord }),
                contentType: 'application/json',
                dataType: 'json',
                success: function (data) {
                    // Lưu thông tin tài khoản và token vào Local Storage để sử dụng cho các lần yêu cầu khác

                    localStorage.setItem('userToken', data.Token);

                    // Chuyển hướng đến trang chủ hoặc trang được yêu cầu trước đó
                    window.location.href = 'https://localhost:44386/Tra/Trangchu';
                },
                error: function (xhr, status, error) {
                    alert('Lỗi đăng nhập: ' + xhr.responseText);
                }
            });
        }
    </script>

</head>

<body>
    <a href="@Url.Action("Login", "Default")" class="sigIn-admin"><i class="fa-solid fa-arrow-left"></i> Sign In to Admin</a>
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-md-6 order-md-2">
                    <img src="~/assets/img/undraw_file_sync_ot38.svg"
                         alt="Image"
                         class="img-fluid" />
                </div>
                <div class="col-md-6 contents">
                    <div class="row justify-content-center">
                        <div class="col-md-8">
                            <div class="mb-4">
                                <h3>Sign In to <strong>User</strong></h3>
                                <p class="mb-4">
                                    Lorem ipsum dolor sit amet elit. Sapiente sit aut eos
                                    consectetur adipisicing.
                                </p>
                            </div>
                            <form action="#" method="post">
                                <div class="form-group first">
                                    <label for="username">Username</label>
                                    <input type="text" class="form-control" id="username" />
                                </div>
                                <div class="form-group last mb-4">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control" id="password" />
                                </div>

                                <div class="d-flex mb-5 align-items-center">
                                    <label class="control control--checkbox mb-0">
                                        <span class="caption">Remember me</span>
                                        <input type="checkbox" checked="checked" />
                                    </label>
                                    <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
                                </div>

                                <button id="btn-login" onclick="Login();">Đăng nhập</button>

                                <span class="d-block text-left my-4 text-muted">
                                    or sign in with
                                </span>

                                <div class="social-login">
                                    <a href="#" class="facebook">
                                        <span class="icon-facebook mr-3"></span>
                                    </a>
                                    <a href="#" class="twitter">
                                        <span class="icon-twitter mr-3"></span>
                                    </a>
                                    <a href="#" class="google">
                                        <span class="icon-google mr-3"></span>
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/assets/js/jquery-3.3.1.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/main.js"></script>
</body>

</html>

WebApplication2/WebApplication2/Views/Default/Register.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <script type="text/javascript" src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/~/assets/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap"
          rel="stylesheet" />

    <link rel="stylesheet" href="~/assets/fonts/icomoon/style.css" />

    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css" />

    <!-- Style -->
    <link rel="stylesheet" href="~/assets/css/styleLogin.css" />

    <title>Users Register</title>


    <script type="text/javascript">
        $(document).ready(function () {
            SortName();
        });
        function SortName() {

            $.ajax({
                url: `https://localhost:44336/api/khachhang/`,
                method: 'GET',
                contentType: 'json',
                dataType: 'json',
                error: function (response) {
                    console.log(response);
                },
                success: function (reponse) {
                    reponse.sort(function (a, b) {
                        var nameA = a.TenKH.toUpperCase(); // Chuyển tên thành chữ in hoa để sắp xếp
                        var nameB = b.TenKH.toUpperCase(); // Chuyển tên thành chữ in hoa để sắp xếp
                        if (nameA < nameB) {
                            return -1;
                        }
                        if (nameA > nameB) {
                            return 1;
                        }
                        return 0;
                    });

                    const len = reponse.length;
                    console.log(reponse);
                    let table = '';
                    for (var i = 0; i < len; ++i) {
                        table = table + '<tr>';

                        table = table + '<td>' + reponse[i].TenKH + '</td>';
                        table = table + '<td>' + reponse[i].Diachi + '</td>';
                        table = table + '<td>' + reponse[i].SDT + '</td>';
                        table = table + '<td>' + reponse[i].Username_khach + '</td>';
                        table = table + '<td>' + reponse[i].Password_khach + '</td>';
                        table = table + '<td>' + reponse[i].MaKH + '</td>';
                        table = table + '</tr>';
                    }
                    $('#allSort').html(table);
                }
            });
        }
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            GetAllKhachhang();
        });
        function GetAllKhachhang() {
            $.ajax({
                url: 'https://localhost:44336/api/khachhang/',
                method: 'GET',
                contentType: 'json',
                dataType: 'json',
                error: function (response) { },
                success: function (reponse) {
                    const len = reponse.length;
                    console.log(reponse);
                    let table = '';
                    for (var i = 0; i < len; ++i) {

                        table = table + '<div class="form-group last mb-4">';
                        table = table + '<label for="username">' + reponse[i].TenKH + '</label>';
                        table = table + '</div>';
                        table = table + ' <div class="form-group last mb-4">';
                        table = table + '<label for="username">' + reponse[i].Diachi + '</label>';
                        table = table + ' <input type="username" class="form-control" id="username" />';
                        table = table + '</div>';
                        table = table + '<div class="form-group first">';

                        table = table + '<label for="username">' + reponse[i].SDT + ' </label>';

                        table = table + ' <input type="text" class="form-control" id="username" />';
                        table = table + ' </div>';
                        table = table + '<div class="form-group last mb-4">';
                        table = table + '<label for="username">' + reponse[i].Username_khach + '</label>';
                        table = table + '</div>';
                        table = table + '<div class="form-group last mb-4">';
                        table = table + '<label for="username">' + reponse[i].Password_khach + '</label>';
                        table = table + '</div>';
                        table = table + '<div class="form-group last mb-4">';
                        table = table + '<label for="username">' + + reponse[i].MaKH + '</label>';
                        table = table + '</div>';






                    }
                    document.getElementById('allKH').innerHTML = table;
                },
                fail: function (response) { }
            });
        }
    </script>

    <script type="text/javascript">
        //Hàm lấy Thêm mới Khách hàng. Dùng $.ajax() thực hiện method HTTPPOST
        function insertKhachHang() {
            var url = 'https://localhost:44336/api/khachhang?name=' + $('input').eq(0).val() +
                '&diachi=' + $('input').eq(1).val() + '&sdt=' + $('input').eq(2).val() +
                '&userkhach=' + $('input').eq(3).val() + '&passkhach=' + $('input').eq(4).val() +
                '&id=' + $('input').eq(5).val();
            $.ajax({
                url: url,
                method: 'POST',
                contentType: 'json',
                dataType: 'json',
                error: function (response) {
                    alert("Đăng ký không thành công");

                },
                success: function (reponse) {
                    alert("Đăng ký thành công");
                    GetAllKhachhang();
                    SortName();
                }
            });
        }
    </script>


</head>
<body>
    
      
        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 order-md-2">
                        <img src="~/assets/img/undraw_file_sync_ot38.svg"
                             alt="Image"
                             class="img-fluid" />
                    </div>
                    <div class="col-md-6 contents">
                        <div class="row justify-content-center">
                            <div class="col-md-8">
                                <div class="mb-4">
                                    
                                  
                                </div>
                                <form action="#" method="post">
                                    <div class="form-group first">
                                        <label for="username">Họ và tên</label>
                                        <input type="text" class="form-control" id="username" />
                                    </div>
                                    <div class="form-group last mb-4">
                                        <label for="username">Địa chỉ</label>
                                        <input type="text" class="form-control" id="username" />
                                    </div>
                                    <div class="form-group first">
                                        <label for="username">Điện thoại </label>
                                        <input type="text" class="form-control" id="username" />
                                    </div>

                                    <div class="form-group first">
                                        <label for="username">Tài khoản</label>
                                        <input type="text" class="form-control" id="username" />
                                    </div>
                                    <div class="form-group last mb-4">
                                        <label for="password">Mật khẩu</label>
                                        <input type="password" class="form-control" id="password" />
                                    </div>
                                    <div class="form-group first">
                                        <label for="password">Nhắc lại mật khẩu</label>
                                        <input type="password" class="form-control" id="password" />
                                    </div>

                                    <div class="d-flex mb-5 align-items-center">
                                        <label class="control control--checkbox mb-0">
                                            <span class="caption">Remember me</span>
                                            <input type="checkbox" checked="checked" />
                                        </label>
                                        <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
                                    </div>

                                    <button class="btn btn-danger rounded" style="background-color: forestgreen;"
                                            onclick="insertKhachHang();">
                                        Đăng ký
                                    </button>
                                    <div>
                                        @Html.ActionLink("Back to Login", "Loginkh")
                                    </div>
                                    <span class="d-block text-left my-4 text-muted">
                                        or sign in with
                                    </span>

                                    <div class="social-login">
                                        <a href="#" class="facebook">
                                            <span class="icon-facebook mr-3"></span>
                                        </a>
                                        <a href="#" class="twitter">
                                            <span class="icon-twitter mr-3"></span>
                                        </a>
                                        <a href="#" class="google">
                                            <span class="icon-google mr-3"></span>
                                        </a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="~/assets/js/jquery-3.3.1.min.js"></script>
        <script src="~/assets/js/popper.min.js"></script>
        <script src="~/assets/js/bootstrap.min.js"></script>
        <script src="~/assets/js/main.js"></script>
</body>
</html>